a = float(input("enter the cost of gas per gallon $="))
b = float(input("enter the number of gallons that was dispensed #="))
total = (a*b)
print("your total spent on gallons of gas is =", total)
input("press enter to end")
