print("   #")
print("  ###")
print( " #___#")
print("| ~__~ |")
print("| ___  |")
print("| | .| |")
print("| |  | |")
print("--------")
print("")
print("")
print("=)")
print("type enter to end")
