a = float(input("enter the cost of gas per gallon $="))
b = float(input("enter the number of gallons that was dispensed #="))
total = (a * b)
sum1 = str(2.0)
print("your {:.2f} spent on gallons of gas is =" .format(total))
input("press enter to end")
